version: '3.8'
services:
  back:
    build: #build_derictory
    depends_on:
      - db
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${PGSQL_DB_NAME:-postgres}
      - DB_USER=${PGSQL_DB_USER:-postgres}
      - DB_PASS=${PGSQL_DB_PASS:-entropy}
    ports:
      - '8080:8080'
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${PGSQL_DB_NAME}
      - POSTGRES_USER=${PGSQL_DB_USER}
      - POSTGRES_PASSWORD=${PGSQL_DB_PASS:-entropy}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
